<script setup>
import { computed, nextTick, ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "../composables/useI18n.js";
import { useAiSettings } from "../composables/useAiSettings.js";

const props = defineProps({
  locale: { type: String, default: "ar-EG" },
});

const { lang, t } = useI18n();
const { aiHeaders } = useAiSettings();
const router = useRouter();

const question = ref("");
const asking = ref(false);
const scanning = ref(false);
const error = ref(null);
const answer = ref(null);
const answerSource = ref(null);
const scanItems = ref([]);
const activeScan = ref(null);
const activeChip = ref(null);
const messagesEl = ref(null);
const open = ref(true);

const chips = computed(() => [
  { id: "ask5", kind: "ask", label: t.value.aiChipAsk5, question: t.value.aiQAsk5 },
  { id: "scalp", kind: "nav", label: t.value.aiChipScalp },
  { id: "top", kind: "ai", type: "top", label: t.value.aiChipTop },
  { id: "accumulation", kind: "ai", type: "accumulation", label: t.value.aiChipAccum },
  { id: "breakout", kind: "ai", type: "breakout", label: t.value.aiChipBreakout },
  { id: "rsi", kind: "ai", type: "rsi", label: t.value.aiChipRsi },
  { id: "macd", kind: "ai", type: "macd", label: t.value.aiChipMacd },
]);

const isScalpScan = computed(() => activeScan.value === "scalp");

// AI badge: true when the answer was generated by the AI agent (vs the
// offline technical scanner fallback).
const byAi = computed(() => answerSource.value === "agent");

// De-duplicate picks by ticker so the same stock never shows twice.
const uniquePicks = computed(() => {
  const seen = new Set();
  const out = [];
  for (const p of answer.value?.picks || []) {
    const key = String(p.ticker || "").toUpperCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(p);
  }
  return out;
});

function fmt(n, d = 2) {
  if (n == null || Number.isNaN(Number(n))) return "—";
  return Number(n).toLocaleString(props.locale, {
    minimumFractionDigits: d,
    maximumFractionDigits: d,
  });
}

function actionLabel(action) {
  return t.value.aiAction[action] || action;
}

async function scrollDown() {
  await nextTick();
  if (messagesEl.value) messagesEl.value.scrollTop = messagesEl.value.scrollHeight;
}

async function runAsk(q) {
  const text = String(q || question.value || "").trim();
  if (!text || asking.value) return;
  question.value = text;
  asking.value = true;
  error.value = null;
  activeScan.value = null;
  scanItems.value = [];
  answerSource.value = null;
  try {
    const res = await fetch("/api/ask", {
      method: "POST",
      headers: { "Content-Type": "application/json", ...aiHeaders() },
      body: JSON.stringify({ question: text, lang: lang.value }),
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
    answer.value = data;
    answerSource.value = data.source || null;
    await scrollDown();
  } catch (err) {
    error.value = err.message;
    answer.value = null;
    answerSource.value = null;
  } finally {
    asking.value = false;
  }
}

async function runScan(type, limit = 10) {
  if (scanning.value) return;
  scanning.value = true;
  error.value = null;
  activeScan.value = type;
  answer.value = null;
  try {
    const res = await fetch(`/api/scan?type=${encodeURIComponent(type)}&limit=${limit}`);
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
    scanItems.value = data.items || [];
    await scrollDown();
  } catch (err) {
    error.value = err.message;
    scanItems.value = [];
  } finally {
    scanning.value = false;
  }
}

function onChip(chip) {
  if (chip.kind === "nav") {
    router.push({ name: "scalp" });
    return;
  }
  activeChip.value = chip.id;
  // Both "ask" and "ai" chips go through the AI-backed /api/ask flow so the
  // response is AI-generated (with fundamentals) — like the recommendations.
  runAsk(chip.kind === "ai" ? t.value.aiQScan(chip.type) : chip.question);
}

function openStock(ticker) {
  const code = String(ticker || "").replace(/\.CA$/i, "");
  if (!code) return;
  router.push({ name: "stock", params: { ticker: code } });
}
</script>

<template>
  <section class="ai-home" :class="{ collapsed: !open }">
    <button
      type="button"
      class="ai-home-head"
      :aria-expanded="open"
      @click="open = !open"
    >
      <div>
        <h2>{{ t.aiAssistTitle }}</h2>
        <p>{{ t.aiAssistLede }}</p>
      </div>
      <span class="ai-home-chevron" :class="{ open }" aria-hidden="true">▾</span>
    </button>

    <div v-show="open" class="ai-home-body">
      <div class="ai-chips" role="group">
        <button
          v-for="chip in chips"
          :key="chip.id"
          type="button"
          class="chip"
          :class="{ active: activeChip === chip.id }"
          :disabled="asking || scanning"
          @click="onChip(chip)"
        >
          {{ chip.label }}
        </button>
      </div>

      <p v-if="error" class="ai-error">{{ t.aiError }}: {{ error }}</p>
      <p v-else-if="asking || scanning" class="ai-status">{{ t.aiLoading }}</p>

      <div ref="messagesEl" class="ai-results">
      <template v-if="answer">
        <div class="ai-source">
          <span class="ai-badge" :class="byAi ? 'ai' : 'scan'">
            {{ byAi ? t.aiByAi : t.aiByScanner }}
          </span>
        </div>
        <p class="ai-answer">{{ answer.answer }}</p>
        <div v-if="uniquePicks.length" class="pick-grid">
          <article
            v-for="pick in uniquePicks"
            :key="pick.ticker"
            class="pick-card"
            :class="pick.action"
            @click="openStock(pick.ticker)"
          >
            <div class="pick-top">
              <strong>{{ pick.ticker }}</strong>
              <span v-if="byAi" class="ai-tag">{{ t.aiTag }}</span>
              <span class="badge">{{ actionLabel(pick.action) }}</span>
              <span class="conf">{{ pick.confidence }}/100</span>
            </div>
            <p class="pick-reason">{{ pick.reason }}</p>
            <dl class="pick-levels">
              <div><dt>{{ t.aiEntry }}</dt><dd>{{ fmt(pick.entry) }}</dd></div>
              <div><dt>{{ t.aiStop }}</dt><dd>{{ fmt(pick.stopLoss) }}</dd></div>
              <div><dt>{{ t.aiT1 }}</dt><dd>{{ fmt(pick.target1) }}</dd></div>
              <div><dt>{{ t.aiT2 }}</dt><dd>{{ fmt(pick.target2) }}</dd></div>
            </dl>
            <p v-if="pick.fundamentals" class="pick-fund">
              {{ t.fPe }} {{ fmt(pick.fundamentals.pe) }}
              · {{ t.fEps }} {{ fmt(pick.fundamentals.eps) }}
            </p>
          </article>
        </div>
        <p v-if="answer.disclaimer" class="ai-disclaimer">{{ answer.disclaimer }}</p>
      </template>

      <template v-else-if="scanItems.length">
        <p class="ai-answer">{{ t.aiScanTitle(activeScan) }}</p>
        <div class="pick-grid">
          <article
            v-for="item in scanItems"
            :key="item.ticker"
            class="pick-card"
            :class="item.score >= 60 ? 'buy' : item.score <= 35 ? 'sell' : 'hold'"
            @click="openStock(item.ticker)"
          >
            <div class="pick-top">
              <strong>{{ item.ticker.replace('.CA', '') }}</strong>
              <span class="conf">{{ item.score }}/100</span>
            </div>
            <p class="pick-name">{{ lang === 'ar' ? item.nameAr : item.nameEn }}</p>
            <p class="pick-reason">{{ item.reasons?.slice(0, 2).join(' · ') }}</p>
            <template v-if="isScalpScan">
              <div class="scalp-prices">
                <div class="scalp-buy">
                  <span>{{ t.scalpBuy }}</span>
                  <strong>{{ fmt(item.scalp?.buy) }}</strong>
                </div>
                <div class="scalp-sell">
                  <span>{{ t.scalpSell }}</span>
                  <strong>{{ fmt(item.scalp?.sell) }}</strong>
                </div>
              </div>
              <dl class="pick-levels">
                <div><dt>{{ t.aiStop }}</dt><dd>{{ fmt(item.scalp?.stop) }}</dd></div>
                <div><dt>{{ t.nowPrice }}</dt><dd>{{ fmt(item.price) }}</dd></div>
                <div><dt>Vol</dt><dd>{{ fmt(item.indicators?.volumeRatio, 1) }}×</dd></div>
                <div><dt>RSI</dt><dd>{{ fmt(item.indicators?.rsi, 1) }}</dd></div>
              </dl>
            </template>
            <template v-else>
              <dl class="pick-levels">
                <div><dt>{{ t.aiEntry }}</dt><dd>{{ fmt(item.trade?.entry) }}</dd></div>
                <div><dt>{{ t.aiStop }}</dt><dd>{{ fmt(item.trade?.stopLoss) }}</dd></div>
                <div><dt>{{ t.aiT1 }}</dt><dd>{{ fmt(item.trade?.target1) }}</dd></div>
                <div><dt>{{ t.aiT2 }}</dt><dd>{{ fmt(item.trade?.target2) }}</dd></div>
              </dl>
              <div class="pick-meta">
                <span>RSI {{ fmt(item.indicators?.rsi, 1) }}</span>
                <span>Vol {{ fmt(item.indicators?.volumeRatio, 1) }}×</span>
                <span>{{ item.indicators?.trend }}</span>
              </div>
            </template>
            <p v-if="item.fundamentals" class="pick-fund">
              {{ t.fPe }} {{ fmt(item.fundamentals.pe) }}
              · {{ t.fEps }} {{ fmt(item.fundamentals.eps) }}
            </p>
          </article>
        </div>
        <p class="ai-disclaimer">{{ t.aiDisclaimer }}</p>
      </template>
      </div>
    </div>
  </section>
</template>
